#!/bin/bash

if echo $1 | grep -Gq '^[0-9]\{1,\}$'
then
	# Epoch to Human Readable Time Conversion
	date --date "@$1" -u "+%Y-%m-%d %H:%M:%S %Z"
elif echo $1 | grep -Gq '^[0-9]\{4\}-[0-9]\{1,2\}-[0-9]\{1,2\}T[0-9]\{1,2\}:[0-9]\{1,2\}:[0-9]\{1,2\}$'
then
	# Human Readable to Epoch Time Conversion
	date --date "$1" "+%s"
else
	# Invalid Input
	echo "Use %Y-%m-%dT%H:%M:%S"
fi
