#!/bin/bash

# fetch random wallpaper from unsplash.it
DIR=$HOME/Pictures/wallpapers
BLURME=1

while :
do
    case $1 in
        --save) SAVE=1; shift; ;;
        *) break; ;;
    esac
done

# backup current wallpaper if needed
if [ "$SAVE" == 1 ]; then
    mkdir -p "$DIR"
    mv "$DIR/today" "$DIR/$(date +'%Y-%m-%d-%H%M%S')-today"
fi

# fetch from unsplash (follow redirect)
curl -o "$DIR/today" -J -L "https://source.unsplash.com/random/1920x1200" > /dev/null 2>&1

# kill blurme script if installed
if [ "$BLURME" == 1 ]; then
    PID=$(pgrep blurme || echo 0)
    if [ "$PID" -ne 0 ]
    then
        echo "killing $PID"
        kill -9 "$PID"
    fi
fi

# set wallpaper with feh
feh --bg-scale "$DIR/today"

# relaunch blurme
if [[ "$BLURME" == 1 && "$PID" -ne 0 ]]; then
    $(which blurme) &
fi
