#!/usr/bin/env zsh

# remove recursively broken symbolics in cwd

local cmd ls links
[[ $+commands[eza] ]] && ls=eza || ls=ls
[[ $+commands[fd] ]] && cmd="fd $1 -t l -L" || cmd="find $1 -xtype l"
IFS=$'\n' links=($(eval "$cmd"))
[[ -z $links ]] && return
$ls -l --color=always ${links[@]}
echo -n "Remove? [y/N]: "
read -q && rm -- ${links[@]}

# vim: ft=sh
