#!/usr/bin/env sh

# zoxide: https://github.com/ajeetdsouza/zoxide
command -v zoxide >/dev/null && {
    export _ZO_EXCLUDE_DIRS="/mnt:/tmp"
    # static loading of zoxide init file (generated by zoxide init zsh)
    [ ! -f "$XDG_CACHE_HOME"/zoxide.zsh ] && zoxide init zsh >"$XDG_CACHE_HOME"/zoxide.zsh
    . "$XDG_CACHE_HOME"/zoxide.zsh
}

# fzf: https://github.com/junegunn/fzf
command -v fzf >/dev/null && {
    # FZF_SHELL_PATH="$GOPATH"/src/github.com/junegunn/fzf/shell
    # shellcheck source=/dev/null
    # . "$FZF_SHELL_PATH"/completion.zsh
    # shellcheck source=/dev/null
    #. "$FZF_SHELL_PATH"/key-bindings.zsh
    # export FZF_DEFAULT_COMMAND='rg --files --hidden --no-require-git'
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --color=always'
    # export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    # FZF_BAT_COMMAND="bat --color=always --style=numbers --line-range :300 {}"
    export FZF_DEFAULT_OPTS="
        --prompt 'λ '
        --layout=reverse
        --margin=1,1
        --bind K:preview-up,J:preview-down
        --bind A:select-all,Z:deselect-all
        --color fg:8,bg:0,hl:1,fg+:7,bg+:0,hl+:1
        --color info:8,prompt:7,spinner:1,pointer:1,marker:1
    "
}

# Docker
command -v docker >/dev/null && {
    . "$ZDOTDIR"/docker/functions.zsh
    . "$ZDOTDIR"/docker/aliases.zsh
    [ -e "$ZDOTDIR"/docker/private.zsh ] && . "$ZDOTDIR"/docker/private.zsh
}
