archive_chat=\33\141
auto_compose=\33\151
backspace=KEY_BACKSPACE
backspace_alt=KEY_ALT_BACKSPACE
backward_kill_word=KEY_CTRLW
backward_word=\4001040
begin_line=KEY_CTRLA
cancel=KEY_CTRL[
clear=KEY_CTRLC
copy=\33\143
cut=\33\170
decrease_list_width=\33\54
delete=KEY_DC
delete_chat=\33\144
delete_line_after_cursor=KEY_CTRLK
delete_line_before_cursor=KEY_CTRLU
delete_msg=KEY_CTRLD
down=KEY_DOWN
edit_msg=KEY_CTRLZ
end=KEY_END
end_line=KEY_CTRLE
ext_call=\33\164
ext_edit=\33\145
find=\33\57
find_next=\33\77
forward_msg=\33\162
forward_word=\4001057
goto_chat=KEY_CTRLF
home=KEY_HOME
increase_list_width=\33\56
jump_pinned=KEY_CTRLP
jump_quoted=\33\161
kill_word=
left=KEY_LEFT
linebreak=KEY_RETURN
next_chat=KEY_CTRLN
next_page=KEY_NPAGE
ok=KEY_RETURN
open=KEY_CTRLV
open_link=
open_msg=\33\167
other_commands_help=KEY_CTRLO
paste=\33\166
pin=\33\160
prev_chat=KEY_CTRLP
prev_page=KEY_PPAGE
quit=KEY_CTRLQ
react=\33\163
right=KEY_RIGHT
save=KEY_CTRLR
select_contact=\33\156
select_emoji=KEY_CTRLS
select_mention=\33\62
send_msg=KEY_CTRLX
spell=\33\44
tab=\33\11
terminal_focus_in=KEY_FOCUS_IN
terminal_focus_out=KEY_FOCUS_OUT
terminal_resize=KEY_RESIZE
toggle_emoji=KEY_CTRLY
toggle_help=KEY_CTRLG
toggle_list=KEY_CTRLL
toggle_top=KEY_NONE
transfer=KEY_CTRLT
unread_chat=KEY_CTRLF
up=KEY_UP
