#!/usr/bin/env sh

echo ":: kitty reload"

# Reload kitten diff
# pgrep -x ruby >/dev/null && \
#     "$XDG_CONFIG_HOME"/wal/generator/kitty.rb

# Reload main theme
kitty_colors=$XDG_CONFIG_HOME/kitty/conf.d/colors.conf
cat "$XDG_CACHE_HOME"/wal/colors-kitty > $kitty_colors
killall -SIGUSR1 kitty
    # alternatives:
    # kitten @ set-colors --all --configured $kitty_colors
    # kitten @ signal-child -m all SIGUSR1
    # kill -s USR1 $KITTY_PID
unset kitty_colors


# Alternative using the kitten theme
# cat "$XDG_CACHE_HOME"/wal/colors-kitty > "$XDG_CONFIG_HOME"/kitty/themes/wal.conf
# kitten themes --reload-in=all Wal

