#!/bin/bash

# fetch random wallpaper from unsplash.it
DIR=$HOME/Pictures/wallpapers
BLURME=1

while :
do
    case $1 in
        --save) SAVE=1; shift; ;;
        *) break; ;;
    esac
done

# backup current wallpaper if needed
if [ "$SAVE" == 1 ]; then
    mkdir -p "$DIR"
    mv "$DIR/today" "$DIR/$(date +'%Y-%m-%d-%H%M%S')-today"
fi

curl -o "$DIR/today" -J -L "https://source.unsplash.com/random/1920x1200" > /dev/null 2>&1

# kill blurme script if installed
/usr/local/bin/chunkc blur::reset

# do the blur stuff myself
# todo

# set wallpaper on all desktop
sqlite3 $HOME/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '$DIR/today'"

# set wallpaper with chunkwm (blur plugin)
# /usr/local/bin/chunkc set wallpaper "$DIR/today"

/usr/local/bin/chunkc blur::wallpaper "$DIR/today"

# convert ~/Pictures/wallpapers/today -blur 0x5 /tmp/chunkwm-blur-global.jpg
/usr/local/bin/chunkc blur::wallpaper set wallpaper_blur
# restart the Dock else the wallpaper wouldn't apply
killall Dock

# relaunch blurme
/usr/local/bin/chunkc blur::enable
