#!/bin/bash

DIR=$HOME/Pictures/wallpapers

while :
do
    case $1 in
        --save) SAVE=1; shift; ;;
        *) break; ;;
    esac
done

mkdir -p "$DIR"

# backup current wallpaper if needed
if [ "$SAVE" == 1 ]; then
    mv "$DIR/today" "$DIR/$(date +'%Y-%m-%d-%H%M%S')-today"
fi

# fetch random wallpaper from unsplash
curl -o "$DIR/today" -J -L "https://source.unsplash.com/random/1920x1200" > /dev/null 2>&1

# set wallpaper on all desktop
sqlite3 $HOME/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '$DIR/today'"

# remove manually wal cache
rm -rf "$HOME/.cache/wal"

# generate colors palette, skipping wallpaper
wal -i "$DIR/today" -n

# change chunkwm focus border
source ~/.cache/wal/colors.sh
NFOCUS=$(echo $color1 | sed 's/#//')
/usr/local/bin/chunkc border::color 0xff$NFOCUS

# change nerdbar colors
osascript $HOME/Library/Application\ Support/Übersicht/widgets/supernerd.widget/scripts/refresh.applescript

# refresh terminal colors
# @see: https://sw.kovidgoyal.net/kitty/remote-control.html#at-set-colors
/Applications/kitty.app/Contents/MacOS/kitty @ set-colors -a -c ~/.cache/wal/colors-kitty-dark.conf

# restart the Dock else the wallpaper wouldn't apply
killall Dock
