#!/bin/bash

d=$'\e[33m'
s=$'\e[32m'
t=$'\e[0m'

read -p "$d [?] Upgrade brew?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    brew update && brew upgrade
    # https://github.com/buo/homebrew-cask-upgrade
    brew cu -ay
    brew cleanup
    brew prune
fi

read -p "$d [?] Upgrade mas?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    mas upgrade
fi

read -p "$d [?] Upgrade dotfiles?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cd "$HOME/dotfiles" && git pull
fi

read -p "$d [?] Upgrade global composer dependencies?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    $(phpenv which composer) global update -d ~/.composer/
fi

read -p "$d [?] Upgrade docker images?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker image ls | grep -v REPOSITORY | awk '{printf("%s:%s\n", $1, $2)}' | xargs -L1 docker pull
    docker system prune -f
fi

read -p "$d [?] Upgrade anyenv?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    anyenv update
fi

read -p "$d [?] Upgrade git workspaces?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cd "$DEVELOPMENT_PATH" && git pull
    repos=($GIT_WORKSPACES)
    for repo in "${repos[@]}"
    do
        echo "$s > Upgrade gws repo $repo...$t"
        cd "$DEVELOPMENT_PATH/$repo" && git pull
    done
fi

read -p "$d [?] Cleanup trash ($(du -sh ~/.Trash/)) and .DS_Store files?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm -rf ~/.Trash/*
    find . -type f -name '*.DS_Store' -ls -delete
fi
