#!/bin/bash

d=$'\e[33m'
s=$'\e[32m'
t=$'\e[0m'

read -p "$d [?] Sync server time?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sudo ntpdate -b time.apple.com
fi

read -p "$d [?] Upgrade brew?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    brew update && brew upgrade
    # https://github.com/buo/homebrew-cask-upgrade
    brew cu -ay
    brew cleanup
    brew prune
fi

read -p "$d [?] Upgrade mas?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    mas upgrade
fi

read -p "$d [?] Upgrade dotfiles?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cd "$HOME/dotfiles" && git pull
fi

read -p "$d [?] Upgrade global composer dependencies?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    $(phpenv which composer) global update -d ~/.composer/
fi

read -p "$d [?] Upgrade global pip dependencies?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    PIP=$(pyenv which pip)
    $PIP freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 $PIP install -U
fi

# read -p "$d [?] Upgrade global npm dependencies?$t" -n 1 -r
# echo    #
# if [[ $REPLY =~ ^[Yy]$ ]]
# then
#     NPM=$(PATH=$HOME/.anyenv/nodenv/shims:$PATH npm)
#     $(NPM) install npm@latest -g
#     $(NPM) outdated -g --depth=0
#     $(NPM) update -g
# fi

read -p "$d [?] Upgrade docker images?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # @HOTFIX: xhyve keeps resetting dns through resolv.conf, cannot pull image
    # https://forums.docker.com/t/custom-etc-resolv-conf-in-docker-for-mac-or-using-dns-domain/10035/7
    echo "nameserver 8.8.8.8" | docker-machine ssh $(docker-machine active) "sudo tee /etc/resolv.conf > /dev/null"

    docker image ls | grep -v REPOSITORY | awk '{printf("%s:%s\n", $1, $2)}' | xargs -L1 docker pull
    docker system prune -f
fi

read -p "$d [?] Upgrade anyenv?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    anyenv update
fi

read -p "$d [?] Upgrade git workspaces?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cd "$DEVELOPMENT_PATH" && git pull
    repos=($GIT_WORKSPACES)
    for repo in "${repos[@]}"
    do
        echo "$s > Upgrade gws repo $repo...$t"
        cd "$DEVELOPMENT_PATH/$repo" && git pull
    done
fi

read -p "$d [?] Cleanup trash ($(du -sh ~/.Trash/)) and .DS_Store files?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm -rf ~/.Trash/*
    find . -type f -name '*.DS_Store' -ls -delete
fi

read -p "$d [?] Change wallpaper?$t" -n 1 -r
echo    #
if [[ $REPLY =~ ^[Yy]$ ]]
then
    sh $HOME/.bin/unsplash
fi