#!/usr/bin/env sh

# Sync repositories and notify user of all upgradable packages with bumped version
#
# foo 1.0 => 1.1
# bar 1.2.12-1 => 1.2.13-1
#
# Cron example (every 3hrs): 0 */3 * * * $HOME/.bin/apt/apt-check

ping -q -c 1 1.1.1.1 >/dev/null || exit

sudo apt update >/dev/null 2>&1 || notify-send -i dialog-error "Error downloading updates."

PKG_REG="a-z+0-9.:\~-"
REGEX="s|\([$PKG_REG]*\)/[a-z,]*\s\([$PKG_REG]*\)\s[a-z0-9]*\s\[upgradable\sfrom:\s\([$PKG_REG]*\)[\w\d-]*\]$|\1 \3 => \2|"
PACKAGES=$(apt list --upgradable 2>/dev/null | grep -v 'Listing...' | sed -e "$REGEX")

if [ "$PACKAGES" ]; then
    COUNT=$(apt list --upgradable 2>/dev/null | grep -v 'Listing...' | sed -e "$REGEX" | wc -l)
    notify-send -i debian-logo "$COUNT update(s) available" "$PACKAGES"
fi
