#!/usr/bin/env sh

# Cleanup the log file before running anything.
cat /dev/null > "$XDG_CACHE_HOME"/xsession-errors

# Init shell if coming from a DM
[ "${XDG_SESSION_TYPE:-tty}" = 'x11' ] && {
    # zsh is my running shell
    [ -z "$ZSH_NAME" ] && exec $SHELL $0 "$@"
    ZHOME=${ZDOTDIR:-$HOME}
    # zshenv is always sourced automatically.
    [ -f "$ZHOME"/.zprofile ] && . "$ZHOME"/.zprofile
    [ -f "$ZHOME"/.zlogin ] && . "$ZHOME"/.zlogin
    emulate -R sh
}

# Store my WM of choice since,
# it will be used in xsession to start selected WM later
export WM=${1:-bspwm}

# Now source global xinitrc file
# The only thing it does is source /etc/X11/Xsession
[ -f /etc/X11/xinit/xinitrc ] && . /etc/X11/xinit/xinitrc
