#!/usr/bin/env sh

_c() { command -v "$1" > /dev/null && "$@"; }
# keyboard delay/rate
_c xset r rate 350 45
# keyboard numlock
_c numlockx on
# current wallpaper/colorscheme
_c theme-select static/random > /dev/null
# default cursor (needs xorg-xsetroot)
_c xsetroot -cursor_name left_ptr

_d() {
    if command -v "$1" > /dev/null 2>&1; then
        pgrep -x "$1" > /dev/null || { "$@" & }
    fi
}
# gtk settings daemon
_d xsettingsd -c $XDG_CONFIG_HOME/xsettingsd/xsettingsd.conf
# clipboard manager
_d clipcatd --no-daemon
# screen locker
_d locker
# music player daemon
_d mpd
# hide mouse cursor
_d xbanish
# reminder
_d remind -z1 -k'notify-send -i bell -u critical Remind %s &' "$XDG_DATA_HOME"/remind
