#!/usr/bin/env sh

_c() { command -v "$1" >/dev/null && "$@"; }
# keyboard delay/rate
_c xset r rate 350 45
# Disable DPMS turning off the screen
# xset -dpms
# xset s off
# Disable bell
# xset b off
# keyboard numlock
_c numlockx on
# keymap
_c toggle-xkbkeymap us
# current wallpaper/colorscheme
_c wal-switcher theme-dark >/dev/null
# default cursor (needs xorg-xsetroot)
_c xsetroot -cursor_name left_ptr

_d() {
    if command -v "$1" >/dev/null 2>&1; then
        pgrep -x "$1" >/dev/null || { "$@" & }
    fi
}
# clipboard manager for rofi
_d greenclip daemon
# screen locker
_d locker
# music player daemon
# _d mpd
# no mouse cursor
_d xbanish
# reminder
_d remind -z1 -k'notify-send -i bell -u critical Remind %s &' "$XDG_DATA_HOME"/remind
