#!/usr/bin/env sh

# update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/bin/i3 1000
# update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/bin/spectrwm 1100
# update-alternatives --set x-window-manager /usr/bin/i3
# exec x-window-manager

# Start WM
session=${WM:-i3}
unset WM
case $session in
    i3|i3wm ) exec i3 2> /tmp/i3.log;;
    bsp|bspwm ) exec bspwm 2> /tmp/bspwm.log;;
    herbsluft|herbstluftwm ) exec herbstluftwm --locked;;
    spectr|spectrwm ) exec spectrwm 2> /tmp/spectrwm.log;;
    subtle|subtlewm ) exec subtle 2> /tmp/subtle.log;;
    awesome|awesomewm ) exec awesome ;;
    * ) exec $session;;
esac

pkill X
