#!/usr/bin/env sh

echo ":: mpv reload"

rgb_to_brg() {
    color=$(xrdb -q | grep -m1 -i "$1" | cut -f2)
    r="$(echo "$color" | cut -c 2-3)"
    g="$(echo "$color" | cut -c 4-5)"
    b="$(echo "$color" | cut -c 6-7)"
    echo "$b$g$r"
}

# Reload custom progress bar (https://github.com/torque/mpv-progressbar)
PB_PATH="$XDG_CONFIG_HOME"/mpv/script-opts/torque-progressbar
mkdir -p "$PB_PATH"

echo "default-style=\\\fnserif\\\bord0\\\shad0\\\fs20\\\c&H$(rgb_to_brg color2)&\\\3c&H$(rgb_to_brg color4)&
bar-height-inactive=3
bar-height-active=10
bar-hide-inactive=yes
bar-default-style=\\\bord0\\\shad0
bar-foreground-style=
bar-cache-style=\\\c&H$(rgb_to_brg color2)&
bar-background-style=\\\c&H$(rgb_to_brg color2)&\\\alpha&HFF&
pause-indicator-foreground-style=\\\c&H$(rgb_to_brg foreground)&
pause-indicator-background-style=\\\c&H$(rgb_to_brg background)&" > "$PB_PATH"/main.conf
