first_name_only = false
show_receipts = true
bell = true
colored_messages = true
default_keybindings = false

[notifications]
enabled = true
show_message_text = true
show_message_chat = true
show_reactions = true
mute_reactions_bell = false

[user]
display_name = "François"

[keybindings.anywhere]
ctrl-q = "quit"

[keybindings.normal]
ctrl-n = "select_channel next"
ctrl-p = "select_channel previous"
ctrl-j = "select_message next entry"
ctrl-k = "select_message previous entry"
ctrl-u = "kill_backward_line"
ctrl-w = "kill_word"
backspace = "delete_character previous"
ctrl-a = "beginning_of_line"
ctrl-e = "end_of_line"
left = "move_text previous character"
right = "move_text next character"
ctrl-h = "move_text previous character"
ctrl-l = "move_text next character"
ctrl-b = "move_text previous word"
ctrl-f = "move_text next word"
# toggle
ctrl-d = "toggle_multiline"
ctrl-shift-m = "toggle_mute_channel"
ctrl-shift-c = "toggle_channel_list"
ctrl-shift-f = "toggle_channel_modal"
# actions
tab = "react"
ctrl-o = "open_file"
ctrl-shift-e = "open_editor"

[keybindings.message_selected]
ctrl-e = "edit_message"
ctrl-y = "copy_message selected"
ctrl-t = "react :thumbsup:"
ctrl-shift-t = "react :heart:"

[keybindings.multiline]
down = "move_text next line"
up = "move_text previous line"
