"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	{ on = "?", run = "help", desc = "Show help" },
	{ on = "<C-i>", run = [ "toggle --state=none" ], desc = "Toggle the current selection state" },
    { on = "y", run = "copy path"},

    { on = [ "1" ], run = "plugin relative-motions 1", desc = "Move in relative steps"},
    { on = [ "2" ], run = "plugin relative-motions 2", desc = "Move in relative steps"},
    { on = [ "3" ], run = "plugin relative-motions 3", desc = "Move in relative steps"},
    { on = [ "4" ], run = "plugin relative-motions 4", desc = "Move in relative steps"},
    { on = [ "5" ], run = "plugin relative-motions 5", desc = "Move in relative steps"},
    { on = [ "6" ], run = "plugin relative-motions 6", desc = "Move in relative steps"},
    { on = [ "7" ], run = "plugin relative-motions 7", desc = "Move in relative steps"},
    { on = [ "8" ], run = "plugin relative-motions 8", desc = "Move in relative steps"},
    { on = [ "9" ], run = "plugin relative-motions 9", desc = "Move in relative steps"},

	{ on = "<C-e>", run = "plugin toggle-pane min-preview", desc = "Toggle preview pane" },
	{ on = "<C-S-e>", run = "plugin toggle-pane max-preview", desc = "Maximize preview pane" },
]
