#!/usr/bin/env sh

# Additional external keyboard commands can be defined
# using a handler program located in $XDG_CONFIG_HOME/nsxiv/exec/key-handler.
# The handler is invoked by pressing Ctrl-x

# Rofi one liner prompt
_prompt() {
    rofi -theme prompt.rasi -dmenu -p "$1 :" -input /dev/null -lines 0
}

while read -r file; do
    case "$1" in
        "C-r")
            name="$(_prompt "Rename")"
            [ "$name" != "" ] && mv "$file" "$(dirname $file)/$name"
            ;;
        "C-d")
            name="$(_prompt "Confirm deletion (y)")"
            [ "$name" = "y" ] && rm -f "$file"
            ;;
        "C-x") rm -f "$file" ;;
        "C-w") ln -sf "$file" "${XDG_PICTURES_DIR:-~/Pictures}"/wallpapers/current \
            && theme-select themes/dark ;;
        "C-m") convert -rotate 90 "$file" "$file" ;;
        "C-p") lp -d "$PRINTER" "$file" ;;
    esac
done
