#!/usr/bin/env sh

# Additional external keyboard commands can be defined
# using a handler program located in $XDG_CONFIG_HOME/nsxiv/exec/key-handler.
# The handler is invoked by pressing Ctrl-x

# Rofi one liner prompt
_prompt() {
    rofi -theme prompt.rasi -dmenu -p "$1 :" -input /dev/null -lines 0
}

while read file; do
    case "$1" in
    "C-r")
        name="$(_prompt "Rename")"
        [ "$name" != "" ] && mv "$file" "$(dirname $file)/$name"
        ;;
    "C-d")
        name="$(_prompt "Confirm deletion (y)")"
        [ "$name" = "y" ] && rm -f "$file"
        ;;
    "C-x") rm -f "$file" ;;
    "C-w") cp -f "$file" "${XDG_PICTURES_DIR:-~/Pictures}"/wallpapers/current && wal-switcher current ;;
    "C-m") convert -rotate 90 "$file" "$file" ;;
    esac
done
