#!/usr/bin/env sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

. "$XDG_CACHE_HOME"/wal/colors.sh
bspc config normal_border_color "$background"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$color1"

# allow the mouse to manipulate windows when the super (mod4) key is pressed
# tiling/floating windows can be resized with left click
# floating windows can be moved with right click
bspc config pointer_modifier mod4
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

# desktop default layouts
bspc desktop ^2 --layout monocle

# nuke the previous rules so reloading the config works as intended
bspc rule -r "*"

# window behaviour
bspc rule -a Sublime_text desktop='^2'
bspc rule -a Firefox desktop='^3'
for app in neomutt weechat skype whatsapp mattermost; do
    bspc rule -a $app desktop='^4'
done

# floating
for app in mpv Firefox:Places Firefox:Browser; do bspc rule -a $app state=floating; done
# center floating, sticky and with a custom size
for app in mailto music-player tremc; do
    bspc rule -a "*:$app" state=floating center=true sticky=true rectangle=930x400+0+0
done
# bottom floating and sticky
for app in '*:*:mpv-webcam' Firefox:Toolkit; do
    bspc rule -a "$app" state=floating sticky=true layer=above manage=off border=off
done

bspc rule -a Zathura state=tiled
bspc rule -a "*:floating" state=floating center=true rectangle=930x400+0+0
bspc rule -a ranger state=floating center=true rectangle=1200x600+0+0
# bspc rule -a Alacritty --one-shot state=floating rectangle=900x500+500+200 focus=on sticky=on && alacritty --class Alacritty --command ranger --selectfile ~/Downloads/$filename

# autostart
polybar-run
