#!/bin/sh

LOCKER="$HOME/.bin/lockscreen3"

if command -v xidlehook &> /dev/null; then
    rm -f /tmp/xidlehook.sock

    pgrep xidlehook > /dev/null || xidlehook \
      --not-when-fullscreen \
      --socket /tmp/xidlehook.sock \
      --timer normal 150 \
        "$HOME/.bin/brightness .5" \
        "$HOME/.bin/brightness 1" \
      `# Dim the screen after 60 seconds, undim if user becomes active` \
      --timer normal 190 \
        "$HOME/.bin/brightness .2" \
        "$HOME/.bin/brightness 1" \
      `# Undim & lock after 10 more seconds` \
      --timer primary 10 \
        "$HOME/.bin/brightness 1; $LOCKER" \
        ''

elif command -v xautolock &> /dev/null; then
    pgrep xautolock > /dev/null || xautolock \
        -detectsleep \
        -time 3 \
        -locker "$LOCKER" \
        -notify 30 \

else
    echo "Locker error: neither xidlehook nor xautolock were found! Aborting." 1>&2
    exit 64
fi
