#!/bin/sh

# colorful ls
# get LS_COLORS file from
# curl -L https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/LS_COLORS > .dircolors

# if [ -t 1 ]; then
    # eval $(dircolors -b ~/.dircolors)
# fi

exec /bin/ls "$@"
