#!/bin/sh

# Fork from https://github.com/addy-dclxvi/almighty-dotfiles/blob/master/.executor/weather
# Did some cleanup, added emojis and managed openweather map credentials from env variable instead

API_ENDPOINT=https://api.openweathermap.org/data/2.5
# Get your own API key here https://openweathermap.org
API_KEY=$OPENWEATHERMAP_APIKEY
# Check on https://openweathermap.org/find
CITY_LAT=$OPENWEATHERMAP_LAT
CITY_LONG=$OPENWEATHERMAP_LONG
SYMBOL_CELSIUS="˚C"
WEATHER_URL="${API_ENDPOINT}/weather?lat=${CITY_LAT}&lon=${CITY_LONG}&appid=${API_KEY}&units=metric"

case "$1" in
    --icon) OWM_SUNNY=" " OWM_CLOUDY=" " OWM_RAINY=" " OWM_STORM=" " OWM_SNOW=" " OWM_FOG=" " OWM_MISC=" " ;;
    --emoji) OWM_SUNNY=☀️ OWM_CLOUDY=☁️ OWM_RAINY=🌧️ OWM_STORM=🌩️ OWM_SNOW=❄️ OWM_FOG=🌫️ OWM_MISC=🐳 ;;
    --text) OWM_SUNNY="Clear" OWM_CLOUDY="Cloudy" OWM_RAINY="Rainy" OWM_STORM="Storm" OWM_SNOW="Snow" OWM_FOG="Fog" OWM_MISC="?" ;;
    *)
        echo "Show current weather by fetching openweathermap API."
        echo ""
        echo "# Usage"
        echo "$ openweathermap [--text|--icon|--emoji]"
        echo ""
        echo "# As a polybar module:"
        echo "[module/openweathermap]"
        echo "type = custom/script"
        echo "interval = 30"
        echo "exec = openweathermap --emoji"
        exit
    ;;
esac

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

case "${WEATHER_MAIN}" in
    *Snow*) echo "${OWM_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
    *Rain*|*Drizzle*) echo "${OWM_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
    *Cloud*) echo "${OWM_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
    *Clear*) echo "${OWM_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
    *Fog*|*Mist*) echo "${OWM_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
    *Thunder*) echo "${OWM_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
    *) echo "${OWM_MISC} ${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
esac
