#!/bin/bash

# credits: https://gist.github.com/naelstrof/f9b74b5221cdc324c0911c89a47b8d97
mkdir -p $SCREENSHOT_PATH
FILENAME=$(date +%s)-$1.png
ICON=/usr/share/icons/Papirus/32x32/categories/spectacle.svg

case $1 in
    screen)
        monitors=$(xrandr | grep -o '[0-9]*x[0-9]*[+-][0-9]*[+-][0-9]*')
        # Get the location of the mouse
        xmouse=$(xdotool getmouselocation | awk -F "[: ]" '{print $2}')
        ymouse=$(xdotool getmouselocation | awk -F "[: ]" '{print $4}')

        for mon in ${monitors}; do
            # Parse the geometry of the monitor
            monw=$(echo ${mon} | awk -F "[x+]" '{print $1}')
            monh=$(echo ${mon} | awk -F "[x+]" '{print $2}')
            monx=$(echo ${mon} | awk -F "[x+]" '{print $3}')
            mony=$(echo ${mon} | awk -F "[x+]" '{print $4}')

            # Use a simple collision check
            if [ $xmouse -gt $monx ]; then
                if (( ${xmouse} <= ${monx}+${monw} )); then
                    if (( ${ymouse} >= ${mony} )); then
                        if (( ${ymouse} <= ${mony}+${monh} )); then
                            # We have found our monitor!
                            maim -g "${monw}x${monh}+${monx}+${mony}" $SCREENSHOT_PATH/$FILENAME &&
                                notify-send -i $ICON "Screenshot" "Copied to $SCREENSHOT_PATH/$FILENAME" ||
                                notify-send -i $ICON "Screenshot" "Failed..."
                        fi
                    fi
                fi
            fi
        done
        ;;

    window)
        maim -i $(xdotool getactivewindow) $SCREENSHOT_PATH/$FILENAME &&
            notify-send -i $ICON "Screenshot" "Copied to $SCREENSHOT_PATH/$FILENAME" ||
            notify-send -i $ICON "Screenshot" "Failed..."
        ;;

    region)
        maim -s -b 1 -c 1,0,0,1 -t 0 -u $SCREENSHOT_PATH/$FILENAME &&
            notify-send -i $ICON "Copied to $SCREENSHOT_PATH/$FILENAME" ||
            notify-send -i $ICON "Screenshot" "Failed..."
        ;;

    region-clipboard)
        maim -s -b 1 -c 1,0,0,1 -t 0 -u | xclip -sel clip -t image/png &&
            notify-send -i $ICON "Screenshot" "Copied to clipboard" ||
            notify-send -i $ICON "Screenshot" "Failed..."
        ;;

    *)
        echo "Invalid argument. Must be one of screen, window or region." >&2
        exit
    ;;
esac
