#!/bin/sh

# Quickly switch between a given keyboard layout and the US Qwerty one
# Credits: https://github.com/fmarier/user-scripts/blob/master/toggle-xkbmap

MAIN_LAYOUT="fr"
CURRENT="$(setxkbmap -query | grep layout | perl -pe 's/^layout: +([^ ]+)$/$1/')"

if [ "$CURRENT" = "us" ] ; then
    setxkbmap -layout "$MAIN_LAYOUT" -option ctrl:nocaps
    CURRENT="$MAIN_LAYOUT"
else
    setxkbmap -layout us -option ctrl:nocaps
    CURRENT="us"
fi

notify-send -i input-keyboard "Keyboard" "Switched to $CURRENT layout"
