#!/bin/bash

# fetch random wallpaper from unsplash.it
# WALLPAPER_PATH=$HOME/Pictures/wallpapers
BLURME=1

while :
do
    case $1 in
        --save) SAVE=1; shift; ;;
        *) break; ;;
    esac
done

mkdir -p "$WALLPAPER_PATH"

# backup current wallpaper if needed
if [[ "$SAVE" == 1  && -f $WALLPAPER_PATH/today ]]; then
    mv "$WALLPAPER_PATH/today" "$WALLPAPER_PATH/$(date +'%Y-%m-%d-%H%M%S')-today"
fi

# fetch from unsplash (follow redirect)
curl -o "$WALLPAPER_PATH/today" -J -L "https://source.unsplash.com/random/1920x1200" > /dev/null 2>&1

# kill blurme script if installed
# if [ "$BLURME" == 1 ]; then
#     PID=$(pgrep blurme || echo 0)
#     if [ "$PID" -ne 0 ]
#     then
#         echo "killing $PID"
#         kill -9 "$PID"
#     fi
# fi

# set wallpaper with feh
# feh --bg-scale "$WALLPAPER_PATH/today"
# rm -rf "$HOME/.cache/wal/"
wal -o ~/.bin/wal-changer -i "$WALLPAPER_PATH/today"

# relaunch blurme
# if [[ "$BLURME" == 1 && "$PID" -ne 0 ]]; then
#     $(which blurme) &
# fi
