#!/bin/bash

WALL="$(<"${HOME}/.cache/wal/wal")"
MIMETYPE=$(file --mime-type -L "$WALL" | tr -d ' ' | awk -F: '{print $2}')

# Set wallpaper
# based on what is set as my wallpaper, this could either be a still picture
# or a cinemagraph. Find out what it is, and launch with the appropriate program.
case "$MIMETYPE" in
*png* | *jpg* | *jpeg*)
    pkill -9 xwinwrap
    feh --bg-fill "$WALL" &
    ;;
*gif* | *webm* | *mp4* | *mkv*) mpvbg "$WALL" &;;
esac

# Reload dunst
pkill dunst
dunst -config ~/.cache/wal/colors-dunstrc &

# Reload lemonbar if any instance is detected
if pgrep -x lemonbar >/dev/null; then
    pkill lemonbar
    sh ~/.config/lemonbar/run &
fi

# Reload kitty instances and +kitten diff
ruby $XDG_CONFIG_HOME/wal/generator/kitty.rb
kitty @ set-colors -a -c $XDG_CACHE_HOME/wal/colors-kitty-dark.conf

# Display notification
notify-send -i preferences-desktop-theme "Appearance" "Theme successfully changed" &
