#!/bin/sh

# Load i3 layout on specific workspace for ncmpcpp player with visualiser and cover art in separate windows
# Dependencies: jq, kitty, sxiv, compton
# https://github.com/ameba23/ncmpcpp_i3_screen_layout
# https://sainathadapa.github.io/blog/i3-empty-workspace-workaround/
# https://sw.kovidgoyal.net/kitty/remote-control.html

WKNAME=5

# workspace exists?
if i3-msg -t get_workspaces | jq ".[] | .name" | grep -q -w $WKNAME; then
    # go to workspace
    i3-msg "workspace $WKNAME"
    i3-msg '[instance="^ncmpcpp$"] focus'
else
    # create workspace and append layout
    i3-msg "workspace $WKNAME; append_layout $HOME/.config/i3/layouts/zik.json"

    # music visualizer
    kitty --name zik_cava cava &

    # music player
    kitty --name zik_ncmpcpp ncmpcpp &
    i3-msg '[instance="^zik_ncmpcpp$"] focus'

    # cover
    # ncmpcpp-art extract
    # feh -^ cover-art -B black -g 256x256+832+600 -Z -x --reload 5 /tmp/cover.jpg &
    sxiv -b -N zik_cover -s f /tmp/cover.jpg &

    # window background opacity
    # note: a clever way would be to tweak compton with this rule
    # "90:class_i %= 'zik_*'"
    # and thus avoid to kill/restart, but somehow kitty
    # sleep 2
    # killall compton
    # compton --daemon
fi

exit 0
