[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst-custom"
rewrite = true
hook = 'pkill dunst; dunst &'

[[items]]
file = "~/.config/kitty/conf.d/colors.conf"
template = "kitty"
rewrite = true
hook = "pkill -USR1 kitty && kitty @ set-colors --all ~/.config/kitty/conf.d/colors.conf"

[[items]]
file = "~/.config/zathura/colors"
template = "zathura"
rewrite = true

[[items]]
file = "~/.config/rofi/colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[items]]
file = "~/.config/xob/styles.cfg"
template = "xob"
subtemplate = "styles"
rewrite = true
hook = "xob-utils"

[[items]]
file = "~/.cache/colors.vim"
template = "vim-custom"
subtemplate = "colors"
rewrite = true
hook = "pgrep -x nvim >/dev/null && pkill -USR1 nvim"

# NOTE: bspwm, i3 and polybar use xresources colors
# reloading the wm take care of the refresh
[[items]]
file = "~/.config/x/Xresources.d/colors"
template = "xresources-custom"
rewrite = true
hook = "xrdb -load ~/.config/x/Xresources; bspc wm -r"
