[highlighting]
# Either the name of a built-in theme (see zsh-patina list-themes) or a string
# in the form `"file:/path/mytheme.toml"` pointing to a custom theme toml file.
theme = "classic"

# Enable or disable dynamic highlighting.
# Can be `true` or `false` or a table with the keys `callables` and `paths`.
dynamic = true
# dynamic = { callables = true, paths = true }

# For performance reasons, highlighting is disabled for very long lines. This
# option specifies the maximum length of a line (in bytes) up to which
# highlighting is applied.
max_line_length = 20000

# The maximum time (in milliseconds) to spend on highlighting a command. If
# highlighting takes longer, it will be aborted and the command will be
# partially highlighted.
#
# Note that the timeout only applies to multi-line commands. Highlighting cannot
# be aborted in the middle of a line. If you often deal with long lines that
# take longer to highlight than the timeout, consider reducing `max_line_length`.
timeout_ms = 500
